version: '3'
services:
  web:
    container_name: tomotomo
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./app/:/app/
    ports:
    - "8080:8080"
